# Multiperiod Heat Integration

**Learning outcome:** Apply multiperiod heat integration through the public `PinchProblem` or `PinchWorkspace` workflow.

**Level:** Intermediate  
**Execution profile:** `base`  
**Expected runtime:** under 2 minutes  
**Optional extras:** none

The lifecycle is explicit: prepare the study, run the named method, then inspect cached results. Observation cells do not launch analysis.

## Study question and data

**Study question:** How do heat-integration targets and equivalent global dt_min values change by operating period, and what is the weighted annual view?

The sample data is packaged with OpenPinch, so the notebook runs without path setup. Read the named inputs and assumptions before substituting plant data.

## Step 1: Run aligned period analyses and scalar/mapped inverse targets

Run this cell once, then inspect its named outputs. Arguments on the method call apply to this analysis; stored configuration is only the fallback when an argument is omitted.

In [1]:
from OpenPinch import PinchProblem

base_problem = PinchProblem(
    "Four-stream-Yee-and-Grossmann-1990-1.json"
)
multiperiod_input = base_problem.to_problem_json()
multiperiod_input["options"]["PROBLEM_PERIOD_IDS"] = [
    "base", "turndown"
]
multiperiod_input["options"]["PROBLEM_PERIOD_WEIGHTS"] = [
    0.7, 0.3
]
for stream in multiperiod_input["streams"]:
    duty = stream["heat_flow"]
    stream["heat_flow"] = {
        "values": [duty["value"], 0.8 * duty["value"]],
        "unit": duty["unit"],
    }
    stream["heat_capacity_flowrate"] = None
problem = PinchProblem(
    multiperiod_input, project_name="Four Stream Periods"
)
period_ids = list(problem.period_ids)
period_outputs = problem.target.all_periods.all_heat_integration()
direct_periods = problem.target.all_periods.direct_heat_integration()
# Enrich the retained period states without solving direct targets again.
period_exergy = problem.target.all_periods.exergy(workers=2)
assert all(
    row.provenance.period_ids == (sid,)
    for sid, output in period_exergy.items() for row in output.targets
)
zero_recovery_dt_mins = problem.target.all_periods.heat_recovery_dt_min(
    heat_recovery=0.0
)
recovery_requests = {
    period_id: result.thermodynamic_limit.value * 0.8
    for period_id, result in zero_recovery_dt_mins.items()
}
mapped_recovery_dt_mins = problem.target.all_periods.heat_recovery_dt_min(
    heat_recovery=recovery_requests, workers=2
)
indirect_periods = problem.target.all_periods.indirect_heat_integration()
site_periods = problem.target.all_periods.total_site_heat_integration()
all_periods = problem.summary_frame(include_periods=True)
assert list(period_outputs) == period_ids
assert len(period_ids) >= 2
all_periods

,Scope,Zone Type,Integration Type,Target Method,Period ID,Hot Utility Target,Cold Utility Target,Heat Recovery,Hot Pinch,Cold Pinch,Hot Utilities,Cold Utilities
0,Site,Site,Process,Heat Exchange,base,300.00 kW,1950.00 kW,5250.00 kW,316.85 degC,316.85 degC,HPS: 300.00 kW,CW: 1950.00 kW
1,Site,Site,Utility,Heat Exchange,base,300.00 kW,1950.00 kW,5250.00 kW,406.84 degC,46.85 degC,HPS: 300.00 kW,CW: 1950.00 kW
2,Site,Site,Process,Heat Exchange,turndown,240.00 kW,1560.00 kW,4200.00 kW,316.85 degC,316.85 degC,HPS: 240.00 kW,CW: 1560.00 kW
3,Site,Site,Utility,Heat Exchange,turndown,240.00 kW,1560.00 kW,4200.00 kW,406.84 degC,46.85 degC,HPS: 240.00 kW,CW: 1560.00 kW

## Step 2: Compare period and weighted summaries

Run this cell once, then inspect its named outputs. Arguments on the method call apply to this analysis; stored configuration is only the fallback when an argument is omitted.

In [2]:
weighted = problem.summary_frame(include_weighted_average=True)
combined = problem.summary_frame(
    include_periods=True, include_weighted_average=True
)
list(problem.period_results)

['base', 'turndown']

## Review the result

Review period results beside the weighted aggregate; the largest single-period target does not necessarily dominate the weighted study.

In [3]:
from IPython.display import display

display(all_periods)
display(zero_recovery_dt_mins)
display(mapped_recovery_dt_mins)
display(weighted)
display(combined)

,Scope,Zone Type,Integration Type,Target Method,Period ID,Hot Utility Target,Cold Utility Target,Heat Recovery,Hot Pinch,Cold Pinch,Hot Utilities,Cold Utilities
0,Site,Site,Process,Heat Exchange,base,300.00 kW,1950.00 kW,5250.00 kW,316.85 degC,316.85 degC,HPS: 300.00 kW,CW: 1950.00 kW
1,Site,Site,Utility,Heat Exchange,base,300.00 kW,1950.00 kW,5250.00 kW,406.84 degC,46.85 degC,HPS: 300.00 kW,CW: 1950.00 kW
2,Site,Site,Process,Heat Exchange,turndown,240.00 kW,1560.00 kW,4200.00 kW,316.85 degC,316.85 degC,HPS: 240.00 kW,CW: 1560.00 kW
3,Site,Site,Utility,Heat Exchange,turndown,240.00 kW,1560.00 kW,4200.00 kW,406.84 degC,46.85 degC,HPS: 240.00 kW,CW: 1560.00 kW

{'base': HeatRecoveryDtMinResult(provenance=AnalysisProvenance(owner_id='5b4cfd83143442a9a867c569766ece4e', method_id='target.heat_recovery_dt_min', zone_address='Site', period_ids=('base',), input_fingerprint='fc9ad02ef07aa13f8418d800f5e1da166bb9a25dabe8e9c5a05bd1f15db216c2', effective_settings_json='{"COSTING_ANNUAL_OP_TIME":8300.0,"COSTING_DISCOUNT_RATE":0.07,"COSTING_HPR_COMP_COST_EXP":1.0,"COSTING_HPR_COMP_FIXED_COST":0.0,"COSTING_HPR_COMP_VARIABLE_COST":10000.0,"COSTING_HPR_ELE_PRICE":200.0,"COSTING_HPR_HX_DUTY_COST_EXP":1.0,"COSTING_HPR_HX_DUTY_FIXED_COST":0.0,"COSTING_HPR_HX_DUTY_VARIABLE_COST":10000.0,"COSTING_HPR_PRICE_RATIO_COLD_TO_ELE":1.0,"COSTING_HPR_PRICE_RATIO_HEAT_TO_ELE":1.0,"COSTING_HX_AREA_COEFF":150.0,"COSTING_HX_AREA_EXP":1.0,"COSTING_HX_UNIT_COST":5500.0,"COSTING_SERVICE_LIFE":20.0,"COSTING_UTILITY_PRICE":100.0,"DIRECT_ASSISTED_HT_DT":10.0,"DIRECT_ASSISTED_HT_ENABLED":false,"DIRECT_BALANCED_CC_ENABLED":true,"DIRECT_VERTICAL_GCC_ENABLED":false,"ENV_PRESSURE":101.0,"ENV_TEMPERATURE":15.0,"HENS_APPROACH_TEMPERATURES":[2.0,4.0,6.0,8.0,10.0,12.0,14.0,16.0,18.0,20.0],"HENS_BEST_SOLUTIONS_TO_SAVE":10,"HENS_DERIVATIVE_THRESHOLDS":[0.5,0.9,1.3,1.7,2.1,2.4,2.8,3.2,3.6,4.0],"HENS_DT_CONT_MULTIPLIERS":null,"HENS_EVM_N_AD_BRANCHES":null,"HENS_EVM_N_RM_BRANCHES":null,"HENS_LOG_LEVEL":"WARNING","HENS_MAX_PARALLEL":10,"HENS_OUTPUT_FOLDER":"","HENS_OUTPUT_FORMATS":[],"HENS_PDM_STAGE_PAIR_LIMIT":null,"HENS_RUN_ID":"Four-stream-Yee-and-Grossmann-1990-1","HENS_SOLVER_EVM":"ipopt-pyomo","HENS_SOLVER_OPTIONS_EVM":{},"HENS_SOLVER_OPTIONS_PDM":{},"HENS_SOLVER_OPTIONS_TDM":{},"HENS_SOLVER_PDM":"couenne","HENS_SOLVER_TDM":"couenne","HENS_SOLVE_TOLERANCE":0.001,"HENS_STAGE_PACKING":"auto","HENS_STAGE_SELECTION":[1,2,3,4],"HENS_SYNTHESIS_QUALITY_TIER":1,"HENS_TDM_PARENT_LIMIT":null,"HPR_BB_MINIMISER":"cmaes","HPR_DT_CASCADE_HX":0.0,"HPR_DT_CONT":0.0,"HPR_DT_ENV_CONT":10.0,"HPR_DT_IHX":0.0,"HPR_ETA_COMP":0.7,"HPR_ETA_EXP":0.7,"HPR_ETA_II_CARNOT":0.5,"HPR_ETA_PENALTY":0.001,"HPR_HE_ETA_II_CARNOT":0.5,"HPR_INITIALISE_SIMULATED_CYCLE":true,"HPR_INTEGRATED_EXPANDER_ENABLED":false,"HPR_LOAD_DUTY":null,"HPR_LOAD_FRACTION":1.0,"HPR_LOAD_MODE":"fraction","HPR_LOAD_PERIOD_VALUES":{},"HPR_MAX_MULTISTART":10,"HPR_MULTIPERIOD_OPTIMIZATION_ENABLED":false,"HPR_MVR_COUNT":1,"HPR_MVR_ETA_COMP":0.7,"HPR_MVR_ETA_MOTOR":0.95,"HPR_MVR_FLUIDS":["Water"],"HPR_N_COND":3,"HPR_N_EVAP":2,"HPR_REFRIGERANTS":["water","ammonia"],"HPR_REFRIGERANT_SORT_ENABLED":true,"HPR_RHO_PENALTY":10.0,"HPR_TYPE":"Cascade Carnot cycles","INPUT_UNIT_DELTA_T":"delta_degC","INPUT_UNIT_ENTHALPY":"kJ/kg","INPUT_UNIT_HEAT_FLOW":"kW","INPUT_UNIT_HTC":"kW/m^2/delta_degC","INPUT_UNIT_PRESSURE":"kPa","INPUT_UNIT_PRICE":"$/MWh","INPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_ANNUAL_COST":"$/y","OUTPUT_UNIT_AREA":"m^2","OUTPUT_UNIT_CAPITAL_COST":"$","OUTPUT_UNIT_EXERGY":"kW","OUTPUT_UNIT_HEAT_FLOW":"kW","OUTPUT_UNIT_HPR_COP":"dimensionless","OUTPUT_UNIT_PERCENT":"%","OUTPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_UTILITY_COST":"$/h","OUTPUT_UNIT_WORK":"kW","POWER_ETA_MECH":1.0,"POWER_HIGH_P_COND_FLASH_ENABLED":false,"POWER_LOAD_FRACTION":1.0,"POWER_MIN_EFF":0.1,"POWER_TURBINE_WORK_ENABLED":false,"POWER_TURB_MODEL":"Medina-Flores et al. (2010)","POWER_TURB_P_IN":90.0,"POWER_TURB_T_IN":450.0,"PROBLEM_PERIOD_IDS":["base","turndown"],"PROBLEM_PERIOD_WEIGHTS":[0.7,0.3],"PROBLEM_TOP_ZONE_IDENTIFIER":"Site","PROBLEM_TOP_ZONE_NAME":"Site","PROCESS_MVR_ETA_COMP":0.7,"PROCESS_MVR_ETA_MOTOR":0.95,"REPORTING_DECIMAL_PLACES":2,"THERMAL_DT_CONT":5.0,"THERMAL_DT_PHASE_CHANGE":0.01,"THERMAL_HTC":1.0,"heat_recovery":0.0}', prerequisite_ids=()), scope='Site', period_id='base', dt_min=HeatRecoveryQuantity(value=300.0, unit='delta_degC'), requested_heat_recovery=HeatRecoveryQuantity(value=0.0, unit='kW'), achieved_heat_recovery=HeatRecoveryQuantity(value=0.0, unit='kW'), thermodynamic_limit=HeatRecoveryQuantity(value=5250.0, unit='kW'), heat_recovery_residual=HeatRecoveryQuantity(value=0.0, unit='kW'), status=<HeatRecoveryDtMinStatus.ZERO_RECOVERY_BOUNDARY: 'zero_recovery_boundary'>, iterations=30),
 'turndown': HeatRecoveryDtMinResult(provenance=AnalysisProvenance(owner_id='5b4cfd83143442a9a867c569766ece4e', method_id='target.heat_recovery_dt_min', zone_address='Site', period_ids=('turndown',), input_fingerprint='fc9ad02ef07aa13f8418d800f5e1da166bb9a25dabe8e9c5a05bd1f15db216c2', effective_settings_json='{"COSTING_ANNUAL_OP_TIME":8300.0,"COSTING_DISCOUNT_RATE":0.07,"COSTING_HPR_COMP_COST_EXP":1.0,"COSTING_HPR_COMP_FIXED_COST":0.0,"COSTING_HPR_COMP_VARIABLE_COST":10000.0,"COSTING_HPR_ELE_PRICE":200.0,"COSTING_HPR_HX_DUTY_COST_EXP":1.0,"COSTING_HPR_HX_DUTY_FIXED_COST":0.0,"COSTING_HPR_HX_DUTY_VARIABLE_COST":10000.0,"COSTING_HPR_PRICE_RATIO_COLD_TO_ELE":1.0,"COSTING_HPR_PRICE_RATIO_HEAT_TO_ELE":1.0,"COSTING_HX_AREA_COEFF":150.0,"COSTING_HX_AREA_EXP":1.0,"COSTING_HX_UNIT_COST":5500.0,"COSTING_SERVICE_LIFE":20.0,"COSTING_UTILITY_PRICE":100.0,"DIRECT_ASSISTED_HT_DT":10.0,"DIRECT_ASSISTED_HT_ENABLED":false,"DIRECT_BALANCED_CC_ENABLED":true,"DIRECT_VERTICAL_GCC_ENABLED":false,"ENV_PRESSURE":101.0,"ENV_TEMPERATURE":15.0,"HENS_APPROACH_TEMPERATURES":[2.0,4.0,6.0,8.0,10.0,12.0,14.0,16.0,18.0,20.0],"HENS_BEST_SOLUTIONS_TO_SAVE":10,"HENS_DERIVATIVE_THRESHOLDS":[0.5,0.9,1.3,1.7,2.1,2.4,2.8,3.2,3.6,4.0],"HENS_DT_CONT_MULTIPLIERS":null,"HENS_EVM_N_AD_BRANCHES":null,"HENS_EVM_N_RM_BRANCHES":null,"HENS_LOG_LEVEL":"WARNING","HENS_MAX_PARALLEL":10,"HENS_OUTPUT_FOLDER":"","HENS_OUTPUT_FORMATS":[],"HENS_PDM_STAGE_PAIR_LIMIT":null,"HENS_RUN_ID":"Four-stream-Yee-and-Grossmann-1990-1","HENS_SOLVER_EVM":"ipopt-pyomo","HENS_SOLVER_OPTIONS_EVM":{},"HENS_SOLVER_OPTIONS_PDM":{},"HENS_SOLVER_OPTIONS_TDM":{},"HENS_SOLVER_PDM":"couenne","HENS_SOLVER_TDM":"couenne","HENS_SOLVE_TOLERANCE":0.001,"HENS_STAGE_PACKING":"auto","HENS_STAGE_SELECTION":[1,2,3,4],"HENS_SYNTHESIS_QUALITY_TIER":1,"HENS_TDM_PARENT_LIMIT":null,"HPR_BB_MINIMISER":"cmaes","HPR_DT_CASCADE_HX":0.0,"HPR_DT_CONT":0.0,"HPR_DT_ENV_CONT":10.0,"HPR_DT_IHX":0.0,"HPR_ETA_COMP":0.7,"HPR_ETA_EXP":0.7,"HPR_ETA_II_CARNOT":0.5,"HPR_ETA_PENALTY":0.001,"HPR_HE_ETA_II_CARNOT":0.5,"HPR_INITIALISE_SIMULATED_CYCLE":true,"HPR_INTEGRATED_EXPANDER_ENABLED":false,"HPR_LOAD_DUTY":null,"HPR_LOAD_FRACTION":1.0,"HPR_LOAD_MODE":"fraction","HPR_LOAD_PERIOD_VALUES":{},"HPR_MAX_MULTISTART":10,"HPR_MULTIPERIOD_OPTIMIZATION_ENABLED":false,"HPR_MVR_COUNT":1,"HPR_MVR_ETA_COMP":0.7,"HPR_MVR_ETA_MOTOR":0.95,"HPR_MVR_FLUIDS":["Water"],"HPR_N_COND":3,"HPR_N_EVAP":2,"HPR_REFRIGERANTS":["water","ammonia"],"HPR_REFRIGERANT_SORT_ENABLED":true,"HPR_RHO_PENALTY":10.0,"HPR_TYPE":"Cascade Carnot cycles","INPUT_UNIT_DELTA_T":"delta_degC","INPUT_UNIT_ENTHALPY":"kJ/kg","INPUT_UNIT_HEAT_FLOW":"kW","INPUT_UNIT_HTC":"kW/m^2/delta_degC","INPUT_UNIT_PRESSURE":"kPa","INPUT_UNIT_PRICE":"$/MWh","INPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_ANNUAL_COST":"$/y","OUTPUT_UNIT_AREA":"m^2","OUTPUT_UNIT_CAPITAL_COST":"$","OUTPUT_UNIT_EXERGY":"kW","OUTPUT_UNIT_HEAT_FLOW":"kW","OUTPUT_UNIT_HPR_COP":"dimensionless","OUTPUT_UNIT_PERCENT":"%","OUTPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_UTILITY_COST":"$/h","OUTPUT_UNIT_WORK":"kW","POWER_ETA_MECH":1.0,"POWER_HIGH_P_COND_FLASH_ENABLED":false,"POWER_LOAD_FRACTION":1.0,"POWER_MIN_EFF":0.1,"POWER_TURBINE_WORK_ENABLED":false,"POWER_TURB_MODEL":"Medina-Flores et al. (2010)","POWER_TURB_P_IN":90.0,"POWER_TURB_T_IN":450.0,"PROBLEM_PERIOD_IDS":["base","turndown"],"PROBLEM_PERIOD_WEIGHTS":[0.7,0.3],"PROBLEM_TOP_ZONE_IDENTIFIER":"Site","PROBLEM_TOP_ZONE_NAME":"Site","PROCESS_MVR_ETA_COMP":0.7,"PROCESS_MVR_ETA_MOTOR":0.95,"REPORTING_DECIMAL_PLACES":2,"THERMAL_DT_CONT":5.0,"THERMAL_DT_PHASE_CHANGE":0.01,"THERMAL_HTC":1.0,"heat_recovery":0.0}', prerequisite_ids=()), scope='Site', period_id='turndown', dt_min=HeatRecoveryQuantity(value=300.0, unit='delta_degC'), requested_heat_recovery=HeatRecoveryQuantity(value=0.0, unit='kW'), achieved_heat_recovery=HeatRecoveryQuantity(value=0.0, unit='kW'), thermodynamic_limit=HeatRecoveryQuantity(value=4200.0, unit='kW'), heat_recovery_residual=HeatRecoveryQuantity(value=0.0, unit='kW'), status=<HeatRecoveryDtMinStatus.ZERO_RECOVERY_BOUNDARY: 'zero_recovery_boundary'>, iterations=30)}

{'base': HeatRecoveryDtMinResult(provenance=AnalysisProvenance(owner_id='5b4cfd83143442a9a867c569766ece4e', method_id='target.heat_recovery_dt_min', zone_address='Site', period_ids=('base',), input_fingerprint='fc9ad02ef07aa13f8418d800f5e1da166bb9a25dabe8e9c5a05bd1f15db216c2', effective_settings_json='{"COSTING_ANNUAL_OP_TIME":8300.0,"COSTING_DISCOUNT_RATE":0.07,"COSTING_HPR_COMP_COST_EXP":1.0,"COSTING_HPR_COMP_FIXED_COST":0.0,"COSTING_HPR_COMP_VARIABLE_COST":10000.0,"COSTING_HPR_ELE_PRICE":200.0,"COSTING_HPR_HX_DUTY_COST_EXP":1.0,"COSTING_HPR_HX_DUTY_FIXED_COST":0.0,"COSTING_HPR_HX_DUTY_VARIABLE_COST":10000.0,"COSTING_HPR_PRICE_RATIO_COLD_TO_ELE":1.0,"COSTING_HPR_PRICE_RATIO_HEAT_TO_ELE":1.0,"COSTING_HX_AREA_COEFF":150.0,"COSTING_HX_AREA_EXP":1.0,"COSTING_HX_UNIT_COST":5500.0,"COSTING_SERVICE_LIFE":20.0,"COSTING_UTILITY_PRICE":100.0,"DIRECT_ASSISTED_HT_DT":10.0,"DIRECT_ASSISTED_HT_ENABLED":false,"DIRECT_BALANCED_CC_ENABLED":true,"DIRECT_VERTICAL_GCC_ENABLED":false,"ENV_PRESSURE":101.0,"ENV_TEMPERATURE":15.0,"HENS_APPROACH_TEMPERATURES":[2.0,4.0,6.0,8.0,10.0,12.0,14.0,16.0,18.0,20.0],"HENS_BEST_SOLUTIONS_TO_SAVE":10,"HENS_DERIVATIVE_THRESHOLDS":[0.5,0.9,1.3,1.7,2.1,2.4,2.8,3.2,3.6,4.0],"HENS_DT_CONT_MULTIPLIERS":null,"HENS_EVM_N_AD_BRANCHES":null,"HENS_EVM_N_RM_BRANCHES":null,"HENS_LOG_LEVEL":"WARNING","HENS_MAX_PARALLEL":10,"HENS_OUTPUT_FOLDER":"","HENS_OUTPUT_FORMATS":[],"HENS_PDM_STAGE_PAIR_LIMIT":null,"HENS_RUN_ID":"Four-stream-Yee-and-Grossmann-1990-1","HENS_SOLVER_EVM":"ipopt-pyomo","HENS_SOLVER_OPTIONS_EVM":{},"HENS_SOLVER_OPTIONS_PDM":{},"HENS_SOLVER_OPTIONS_TDM":{},"HENS_SOLVER_PDM":"couenne","HENS_SOLVER_TDM":"couenne","HENS_SOLVE_TOLERANCE":0.001,"HENS_STAGE_PACKING":"auto","HENS_STAGE_SELECTION":[1,2,3,4],"HENS_SYNTHESIS_QUALITY_TIER":1,"HENS_TDM_PARENT_LIMIT":null,"HPR_BB_MINIMISER":"cmaes","HPR_DT_CASCADE_HX":0.0,"HPR_DT_CONT":0.0,"HPR_DT_ENV_CONT":10.0,"HPR_DT_IHX":0.0,"HPR_ETA_COMP":0.7,"HPR_ETA_EXP":0.7,"HPR_ETA_II_CARNOT":0.5,"HPR_ETA_PENALTY":0.001,"HPR_HE_ETA_II_CARNOT":0.5,"HPR_INITIALISE_SIMULATED_CYCLE":true,"HPR_INTEGRATED_EXPANDER_ENABLED":false,"HPR_LOAD_DUTY":null,"HPR_LOAD_FRACTION":1.0,"HPR_LOAD_MODE":"fraction","HPR_LOAD_PERIOD_VALUES":{},"HPR_MAX_MULTISTART":10,"HPR_MULTIPERIOD_OPTIMIZATION_ENABLED":false,"HPR_MVR_COUNT":1,"HPR_MVR_ETA_COMP":0.7,"HPR_MVR_ETA_MOTOR":0.95,"HPR_MVR_FLUIDS":["Water"],"HPR_N_COND":3,"HPR_N_EVAP":2,"HPR_REFRIGERANTS":["water","ammonia"],"HPR_REFRIGERANT_SORT_ENABLED":true,"HPR_RHO_PENALTY":10.0,"HPR_TYPE":"Cascade Carnot cycles","INPUT_UNIT_DELTA_T":"delta_degC","INPUT_UNIT_ENTHALPY":"kJ/kg","INPUT_UNIT_HEAT_FLOW":"kW","INPUT_UNIT_HTC":"kW/m^2/delta_degC","INPUT_UNIT_PRESSURE":"kPa","INPUT_UNIT_PRICE":"$/MWh","INPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_ANNUAL_COST":"$/y","OUTPUT_UNIT_AREA":"m^2","OUTPUT_UNIT_CAPITAL_COST":"$","OUTPUT_UNIT_EXERGY":"kW","OUTPUT_UNIT_HEAT_FLOW":"kW","OUTPUT_UNIT_HPR_COP":"dimensionless","OUTPUT_UNIT_PERCENT":"%","OUTPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_UTILITY_COST":"$/h","OUTPUT_UNIT_WORK":"kW","POWER_ETA_MECH":1.0,"POWER_HIGH_P_COND_FLASH_ENABLED":false,"POWER_LOAD_FRACTION":1.0,"POWER_MIN_EFF":0.1,"POWER_TURBINE_WORK_ENABLED":false,"POWER_TURB_MODEL":"Medina-Flores et al. (2010)","POWER_TURB_P_IN":90.0,"POWER_TURB_T_IN":450.0,"PROBLEM_PERIOD_IDS":["base","turndown"],"PROBLEM_PERIOD_WEIGHTS":[0.7,0.3],"PROBLEM_TOP_ZONE_IDENTIFIER":"Site","PROBLEM_TOP_ZONE_NAME":"Site","PROCESS_MVR_ETA_COMP":0.7,"PROCESS_MVR_ETA_MOTOR":0.95,"REPORTING_DECIMAL_PLACES":2,"THERMAL_DT_CONT":5.0,"THERMAL_DT_PHASE_CHANGE":0.01,"THERMAL_HTC":1.0,"heat_recovery":4200.0}', prerequisite_ids=()), scope='Site', period_id='base', dt_min=HeatRecoveryQuantity(value=70.00000029802322, unit='delta_degC'), requested_heat_recovery=HeatRecoveryQuantity(value=4200.0, unit='kW'), achieved_heat_recovery=HeatRecoveryQuantity(value=4199.99999552965, unit='kW'), thermodynamic_limit=HeatRecoveryQuantity(value=5250.0, unit='kW'), heat_recovery_residual=HeatRecoveryQuantity(value=-4.4703501771437e-06, unit='kW'), status=<HeatRecoveryDtMinStatus.SOLVED: 'solved'>, iterations=30),
 'turndown': HeatRecoveryDtMinResult(provenance=AnalysisProvenance(owner_id='5b4cfd83143442a9a867c569766ece4e', method_id='target.heat_recovery_dt_min', zone_address='Site', period_ids=('turndown',), input_fingerprint='fc9ad02ef07aa13f8418d800f5e1da166bb9a25dabe8e9c5a05bd1f15db216c2', effective_settings_json='{"COSTING_ANNUAL_OP_TIME":8300.0,"COSTING_DISCOUNT_RATE":0.07,"COSTING_HPR_COMP_COST_EXP":1.0,"COSTING_HPR_COMP_FIXED_COST":0.0,"COSTING_HPR_COMP_VARIABLE_COST":10000.0,"COSTING_HPR_ELE_PRICE":200.0,"COSTING_HPR_HX_DUTY_COST_EXP":1.0,"COSTING_HPR_HX_DUTY_FIXED_COST":0.0,"COSTING_HPR_HX_DUTY_VARIABLE_COST":10000.0,"COSTING_HPR_PRICE_RATIO_COLD_TO_ELE":1.0,"COSTING_HPR_PRICE_RATIO_HEAT_TO_ELE":1.0,"COSTING_HX_AREA_COEFF":150.0,"COSTING_HX_AREA_EXP":1.0,"COSTING_HX_UNIT_COST":5500.0,"COSTING_SERVICE_LIFE":20.0,"COSTING_UTILITY_PRICE":100.0,"DIRECT_ASSISTED_HT_DT":10.0,"DIRECT_ASSISTED_HT_ENABLED":false,"DIRECT_BALANCED_CC_ENABLED":true,"DIRECT_VERTICAL_GCC_ENABLED":false,"ENV_PRESSURE":101.0,"ENV_TEMPERATURE":15.0,"HENS_APPROACH_TEMPERATURES":[2.0,4.0,6.0,8.0,10.0,12.0,14.0,16.0,18.0,20.0],"HENS_BEST_SOLUTIONS_TO_SAVE":10,"HENS_DERIVATIVE_THRESHOLDS":[0.5,0.9,1.3,1.7,2.1,2.4,2.8,3.2,3.6,4.0],"HENS_DT_CONT_MULTIPLIERS":null,"HENS_EVM_N_AD_BRANCHES":null,"HENS_EVM_N_RM_BRANCHES":null,"HENS_LOG_LEVEL":"WARNING","HENS_MAX_PARALLEL":10,"HENS_OUTPUT_FOLDER":"","HENS_OUTPUT_FORMATS":[],"HENS_PDM_STAGE_PAIR_LIMIT":null,"HENS_RUN_ID":"Four-stream-Yee-and-Grossmann-1990-1","HENS_SOLVER_EVM":"ipopt-pyomo","HENS_SOLVER_OPTIONS_EVM":{},"HENS_SOLVER_OPTIONS_PDM":{},"HENS_SOLVER_OPTIONS_TDM":{},"HENS_SOLVER_PDM":"couenne","HENS_SOLVER_TDM":"couenne","HENS_SOLVE_TOLERANCE":0.001,"HENS_STAGE_PACKING":"auto","HENS_STAGE_SELECTION":[1,2,3,4],"HENS_SYNTHESIS_QUALITY_TIER":1,"HENS_TDM_PARENT_LIMIT":null,"HPR_BB_MINIMISER":"cmaes","HPR_DT_CASCADE_HX":0.0,"HPR_DT_CONT":0.0,"HPR_DT_ENV_CONT":10.0,"HPR_DT_IHX":0.0,"HPR_ETA_COMP":0.7,"HPR_ETA_EXP":0.7,"HPR_ETA_II_CARNOT":0.5,"HPR_ETA_PENALTY":0.001,"HPR_HE_ETA_II_CARNOT":0.5,"HPR_INITIALISE_SIMULATED_CYCLE":true,"HPR_INTEGRATED_EXPANDER_ENABLED":false,"HPR_LOAD_DUTY":null,"HPR_LOAD_FRACTION":1.0,"HPR_LOAD_MODE":"fraction","HPR_LOAD_PERIOD_VALUES":{},"HPR_MAX_MULTISTART":10,"HPR_MULTIPERIOD_OPTIMIZATION_ENABLED":false,"HPR_MVR_COUNT":1,"HPR_MVR_ETA_COMP":0.7,"HPR_MVR_ETA_MOTOR":0.95,"HPR_MVR_FLUIDS":["Water"],"HPR_N_COND":3,"HPR_N_EVAP":2,"HPR_REFRIGERANTS":["water","ammonia"],"HPR_REFRIGERANT_SORT_ENABLED":true,"HPR_RHO_PENALTY":10.0,"HPR_TYPE":"Cascade Carnot cycles","INPUT_UNIT_DELTA_T":"delta_degC","INPUT_UNIT_ENTHALPY":"kJ/kg","INPUT_UNIT_HEAT_FLOW":"kW","INPUT_UNIT_HTC":"kW/m^2/delta_degC","INPUT_UNIT_PRESSURE":"kPa","INPUT_UNIT_PRICE":"$/MWh","INPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_ANNUAL_COST":"$/y","OUTPUT_UNIT_AREA":"m^2","OUTPUT_UNIT_CAPITAL_COST":"$","OUTPUT_UNIT_EXERGY":"kW","OUTPUT_UNIT_HEAT_FLOW":"kW","OUTPUT_UNIT_HPR_COP":"dimensionless","OUTPUT_UNIT_PERCENT":"%","OUTPUT_UNIT_TEMPERATURE":"degC","OUTPUT_UNIT_UTILITY_COST":"$/h","OUTPUT_UNIT_WORK":"kW","POWER_ETA_MECH":1.0,"POWER_HIGH_P_COND_FLASH_ENABLED":false,"POWER_LOAD_FRACTION":1.0,"POWER_MIN_EFF":0.1,"POWER_TURBINE_WORK_ENABLED":false,"POWER_TURB_MODEL":"Medina-Flores et al. (2010)","POWER_TURB_P_IN":90.0,"POWER_TURB_T_IN":450.0,"PROBLEM_PERIOD_IDS":["base","turndown"],"PROBLEM_PERIOD_WEIGHTS":[0.7,0.3],"PROBLEM_TOP_ZONE_IDENTIFIER":"Site","PROBLEM_TOP_ZONE_NAME":"Site","PROCESS_MVR_ETA_COMP":0.7,"PROCESS_MVR_ETA_MOTOR":0.95,"REPORTING_DECIMAL_PLACES":2,"THERMAL_DT_CONT":5.0,"THERMAL_DT_PHASE_CHANGE":0.01,"THERMAL_HTC":1.0,"heat_recovery":3360.0}', prerequisite_ids=()), scope='Site', period_id='turndown', dt_min=HeatRecoveryQuantity(value=70.00000029802322, unit='delta_degC'), requested_heat_recovery=HeatRecoveryQuantity(value=3360.0, unit='kW'), achieved_heat_recovery=HeatRecoveryQuantity(value=3359.99999642372, unit='kW'), thermodynamic_limit=HeatRecoveryQuantity(value=4200.0, unit='kW'), heat_recovery_residual=HeatRecoveryQuantity(value=-3.57628005076549e-06, unit='kW'), status=<HeatRecoveryDtMinStatus.SOLVED: 'solved'>, iterations=30)}

,Scope,Zone Type,Integration Type,Target Method,Period ID,Hot Utility Target,Cold Utility Target,Heat Recovery,Hot Pinch,Cold Pinch,Hot Utilities,Cold Utilities
0,Site,Site,Process,Heat Exchange,weighted_average,282.00 kW,1833.00 kW,4935.00 kW,316.85 degC,316.85 degC,HPS: 282.00 kW,CW: 1833.00 kW
1,Site,Site,Utility,Heat Exchange,weighted_average,282.00 kW,1833.00 kW,4935.00 kW,406.84 degC,46.85 degC,HPS: 282.00 kW,CW: 1833.00 kW

,Scope,Zone Type,Integration Type,Target Method,Period ID,Hot Utility Target,Cold Utility Target,Heat Recovery,Hot Pinch,Cold Pinch,Hot Utilities,Cold Utilities
0,Site,Site,Process,Heat Exchange,base,300.00 kW,1950.00 kW,5250.00 kW,316.85 degC,316.85 degC,HPS: 300.00 kW,CW: 1950.00 kW
1,Site,Site,Utility,Heat Exchange,base,300.00 kW,1950.00 kW,5250.00 kW,406.84 degC,46.85 degC,HPS: 300.00 kW,CW: 1950.00 kW
2,Site,Site,Process,Heat Exchange,turndown,240.00 kW,1560.00 kW,4200.00 kW,316.85 degC,316.85 degC,HPS: 240.00 kW,CW: 1560.00 kW
3,Site,Site,Utility,Heat Exchange,turndown,240.00 kW,1560.00 kW,4200.00 kW,406.84 degC,46.85 degC,HPS: 240.00 kW,CW: 1560.00 kW
4,Site,Site,Process,Heat Exchange,weighted_average,282.00 kW,1833.00 kW,4935.00 kW,316.85 degC,316.85 degC,HPS: 282.00 kW,CW: 1833.00 kW
5,Site,Site,Utility,Heat Exchange,weighted_average,282.00 kW,1833.00 kW,4935.00 kW,406.84 degC,46.85 degC,HPS: 282.00 kW,CW: 1833.00 kW

## Interpret the result

Review every period before the weighted average; use a scalar recovery only when broadcasting the same requirement is intentional, and use an exact period mapping otherwise.

## Adapt this template

Replace the sample with period-tagged plant data and verify period order and weights before comparing annual totals.

Keep the workflow explicit: prepare input, call one named engineering method, inspect cached results, then export.