# Area Cost and Exergy

**Learning outcome:** Apply area cost and exergy through the public `PinchProblem` or `PinchWorkspace` workflow.

**Level:** Intermediate  
**Execution profile:** `base`  
**Expected runtime:** under 2 minutes  
**Optional extras:** plot

The lifecycle is explicit: prepare the study, run the named method, then inspect cached results. Observation cells do not launch analysis.

## Study question and data

**Study question:** How do energy targets translate into exchanger area, cost, and thermodynamic quality?

The sample data is packaged with OpenPinch, so the notebook runs without path setup. Read the named inputs and assumptions before substituting plant data.

## Step 1: Estimate area and cost

Run this cell once, then inspect its named outputs. Arguments on the method call apply to this analysis; stored configuration is only the fallback when an argument is omitted.

In [1]:
from OpenPinch import PinchProblem

problem = PinchProblem("basic_pinch.json", project_name="Site")
area_cost = problem.target.heat_exchanger_area_and_cost()
area_cost_summary = problem.summary_frame()
area_cost_summary

,Scope,Zone Type,Integration Type,Target Method,Period ID,Hot Utility Target,Cold Utility Target,Heat Recovery,Hot Pinch,Cold Pinch,Hot Utilities,Cold Utilities
0,Site,Site,Process,Heat Exchange,0,750.00 kW,1000.00 kW,5150.00 kW,145.00 degC,145.00 degC,HU: 750.00 kW,CU: 1000.00 kW

## Step 2: Add exergy and period views

Run this cell once, then inspect its named outputs. Arguments on the method call apply to this analysis; stored configuration is only the fallback when an argument is omitted.

In [2]:
base_target = problem.target.direct_heat_integration()
exergy = problem.target.exergy(
    base_target=base_target, options={"ENV_TEMPERATURE": 25.0}
)
assert exergy.provenance.effective_settings["ENV_TEMPERATURE"] == 25.0
period_area_cost = problem.target.all_periods.heat_exchanger_area_and_cost()
period_exergy = problem.target.all_periods.exergy()
exergy_curve = problem.plot.exergetic_grand_composite_curve()
exergy_loads = problem.plot.exergetic_net_load_profiles()

## Review the result

Read the area and cost summary together with the exergy views to avoid selecting a design from energy targets alone.

In [3]:
from IPython.display import display

display(area_cost_summary)
display(exergy_curve)
display(exergy_loads)

,Scope,Zone Type,Integration Type,Target Method,Period ID,Hot Utility Target,Cold Utility Target,Heat Recovery,Hot Pinch,Cold Pinch,Hot Utilities,Cold Utilities
0,Site,Site,Process,Heat Exchange,0,750.00 kW,1000.00 kW,5150.00 kW,145.00 degC,145.00 degC,HU: 750.00 kW,CU: 1000.00 kW

## Interpret the result

Treat area and exergy as complementary screens: area exposes transfer difficulty, while exergy exposes quality loss.

## Adapt this template

Supply your economic and film-coefficient assumptions through explicit arguments or stored fallback configuration.

Keep the workflow explicit: prepare input, call one named engineering method, inspect cached results, then export.